title: "Chenrui Zhang | Yunnan University"
page-top-title: Chenrui Zhang
top-section-bg-text: Economics & Finance
backgrounds:
  - static/assets/background/background_0.jpeg
background-interval-ms: 7000
background-overlay: 0.48
copyright-text: '&copy; Chenrui Zhang 2026. All Rights Reserved.'
sections:
  - id: home
    nav: HOME
    title: Chenrui Zhang&ensp;|&ensp;张宸瑞
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: RESEARCH
    title: RESEARCH
    icon: bi-file-text-fill
  - id: teaching
    nav: TEACHING
    title: TEACHING
    icon: bi-book-fill
